apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  namespace: {{ .Release.Namespace }}
spec:
  containers:
  - name: my-container
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: {{ .Release.Name }}-config
          key: APP_MESSAGE
79cd9a2f06022a8529993221205333ba03e22960
