apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: default
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_MESSAGE